/*
 * JanelaPrincipal.java
 *
 * Created on 2 de Setembro de 2006, 19:33
 */

package jtable;

import dados.Host;
import java.util.*;
import javax.swing.table.*;

/**
 *
 * @author  fernando
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    private List<Host> hosts = new ArrayList<Host>();
    
    /** Creates new form JanelaPrincipal */
    public JanelaPrincipal() {
        initComponents();
        /*
        SistemaOperacionalTableCellRenderer cellRenderer = new SistemaOperacionalTableCellRenderer();
        tabelaHosts.setDefaultRenderer(SistemaOperacional.class, cellRenderer);
        tabelaHosts.setRowHeight(cellRenderer.getIconHeight());
        */
    }

    public List<Host> getHosts() {
        return hosts;
    }

    public void setHosts(List<Host> hosts) {
        this.hosts = hosts;
        ((HostJTable)tabelaHosts).setHosts(hosts);
        //tabelaHosts.setModel(new HostTableModel(hosts));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHosts = new HostJTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Java Magazine - Demo do JTable");
        tabelaHosts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabelaHosts.setAutoCreateColumnsFromModel(false);
        jScrollPane1.setViewportView(tabelaHosts);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHosts;
    // End of variables declaration//GEN-END:variables
    
}
