/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadPerfil.java
 *
 * Created on 06/07/2011, 10:36:34
 */
package br.com.devmax.sisgvc.visao;

import br.com.devmax.sisgvc.controle.Controle;
import br.com.devmax.sisgvc.daos.CidadeDAO;
import br.com.devmax.sisgvc.daos.ClienteDAO;
import br.com.devmax.sisgvc.modelo.CidadeBean;
import br.com.devmax.sisgvc.modelo.ClienteBean;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel; 

/**
 *
 * @author Maxwell
 */
public class FrmCadCliente extends javax.swing.JDialog {

    /** Creates new form FrmCadPerfil */
    public FrmCadCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        InicializarTabela();
        carregaCbCidades();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbRG = new javax.swing.JLabel();
        tfRg = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        ftfCpf = new javax.swing.JFormattedTextField();
        lbNascimento = new javax.swing.JLabel();
        ftfNascimento = new javax.swing.JFormattedTextField();
        lbLogradouro = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        lbBairro = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        lbUf = new javax.swing.JLabel();
        lbCep = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        lbTelefone = new javax.swing.JLabel();
        ftfTelefone = new javax.swing.JFormattedTextField();
        lbCelular = new javax.swing.JLabel();
        ftfCelular = new javax.swing.JFormattedTextField();
        cbCidade = new javax.swing.JComboBox();
        tfUf = new javax.swing.JTextField();
        btEditCidade = new javax.swing.JButton();
        lbCorCasa = new javax.swing.JLabel();
        tfCorCasa = new javax.swing.JTextField();
        tfNrFrente = new javax.swing.JTextField();
        lbNrFrente = new javax.swing.JLabel();
        tfNrLado = new javax.swing.JTextField();
        lbNrLado = new javax.swing.JLabel();
        tfReferencia = new javax.swing.JTextField();
        lbReferencia = new javax.swing.JLabel();
        lbApelido = new javax.swing.JLabel();
        tfApelido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISGVC - Sistema Gerenciador de Vendas por Consignação");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/file-new-16x16.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        painelBotoes.add(btNovo);

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/edit-16x16.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        painelBotoes.add(btEditar);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/edit-delete-16x16.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        painelBotoes.add(btExcluir);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/file-save-16x16.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        painelBotoes.add(btSalvar);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbClientes.setModel(tableModel);
        jScrollPane1.setViewportView(tbClientes);

        lbNome.setText("Nome:");

        tfNome.setEnabled(false);

        lbRG.setText("RG:");

        tfRg.setEnabled(false);

        lbCpf.setText("CPF:");

        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCpf.setEnabled(false);

        lbNascimento.setText("Nascimento:");

        try {
            ftfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfNascimento.setEnabled(false);

        lbLogradouro.setText("Logradouro:");

        tfLogradouro.setEnabled(false);

        lbNumero.setText("Nº:");

        tfNumero.setEnabled(false);

        lbBairro.setText("Bairro:");

        tfBairro.setEnabled(false);

        lbCidade.setText("Cidade:");

        lbUf.setText("UF:");

        lbCep.setText("CEP:");

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCep.setEnabled(false);

        lbTelefone.setText("Telefone:");

        try {
            ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelefone.setEnabled(false);
        ftfTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        lbCelular.setText("Celular:");

        try {
            ftfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCelular.setEnabled(false);
        ftfCelular.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        cbCidade.setEnabled(false);
        cbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCidadeActionPerformed(evt);
            }
        });

        tfUf.setEnabled(false);

        btEditCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/7184_16x16.png"))); // NOI18N
        btEditCidade.setEnabled(false);
        btEditCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditCidadeActionPerformed(evt);
            }
        });

        lbCorCasa.setText("Cor da casa:");

        tfCorCasa.setEnabled(false);

        tfNrFrente.setEnabled(false);

        lbNrFrente.setText("Nº da frente:");

        tfNrLado.setEnabled(false);

        lbNrLado.setText("Nº ao lado:");

        tfReferencia.setEnabled(false);

        lbReferencia.setText("Ponto de referência:");

        lbApelido.setText("Apelido:");

        tfApelido.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNome)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbRG, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCpf))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNascimento)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfLogradouro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbLogradouro, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNumero))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbBairro)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btEditCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbCidade))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbUf)
                                    .addComponent(tfUf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCep)
                                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCorCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCorCasa))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbNrFrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNrFrente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNrLado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNrLado))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbReferencia)
                                    .addComponent(tfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbApelido)
                                    .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTelefone))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCelular)
                                    .addComponent(ftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbLogradouro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNumero)
                                    .addComponent(lbBairro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCep, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCidade, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEditCidade, 0, 0, Short.MAX_VALUE)
                            .addComponent(tfUf)
                            .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorCasa)
                    .addComponent(lbNrFrente)
                    .addComponent(lbNrLado)
                    .addComponent(lbReferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCorCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNrFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNrLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbApelido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTelefone)
                            .addComponent(lbCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btEditCidade, cbCidade, ftfCep, tfUf});

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/User-Group-32_1.png"))); // NOI18N
        jLabel1.setText("Cadastro de Clientes");

        tfBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBusca)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(939, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novoCliente();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        editarCliente();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirCliente();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        reiniciaTela();
        tfBusca.setText("");
    }//GEN-LAST:event_formWindowClosing

    private void cbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCidadeActionPerformed
        if(cbCidade.getSelectedIndex()==0){
            tfUf.setText("");
            clienteBean.setCidade(null);
        }else{
            setaCidadeBean(); 
        }
    }//GEN-LAST:event_cbCidadeActionPerformed

    private void btEditCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditCidadeActionPerformed
        Controle.abreFrmCadCidades();
    }//GEN-LAST:event_btEditCidadeActionPerformed

    private void tfBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscaKeyReleased
        atualizarDadosDaTabela();
        tfBusca.requestFocus();
    }//GEN-LAST:event_tfBuscaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditCidade;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JFormattedTextField ftfCelular;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JFormattedTextField ftfCpf;
    private javax.swing.JFormattedTextField ftfNascimento;
    private javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbApelido;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCorCasa;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbNascimento;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNrFrente;
    private javax.swing.JLabel lbNrLado;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbRG;
    private javax.swing.JLabel lbReferencia;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbUf;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField tfApelido;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfBusca;
    private javax.swing.JTextField tfCorCasa;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNrFrente;
    private javax.swing.JTextField tfNrLado;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfReferencia;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfUf;
    // End of variables declaration//GEN-END:variables
    private static List<ClienteBean> lista = new ArrayList<ClienteBean>();
    private static ClienteBean clienteBean = new ClienteBean();
    private static List<CidadeBean> cidades = new ArrayList<CidadeBean>();
    //-Código referente a tabela--------------------------------------------------------------------------------
    private DefaultTableModel tableModel = new DefaultTableModel(null, new String[]{"Nome"});
    private ListSelectionModel lms;
    private int operacao = 0;//se 1: novo, se 2: editar

    private void tbLinhaSelecionada(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            clienteBean.setId(lista.get(tbClientes.getSelectedRow()).getId());
            tfNome.setText(lista.get(tbClientes.getSelectedRow()).getNome());
            tfRg.setText(lista.get(tbClientes.getSelectedRow()).getRg());
            ftfCpf.setText(lista.get(tbClientes.getSelectedRow()).getCpf());
            ftfNascimento.setText(lista.get(tbClientes.getSelectedRow()).getDataNascimentoStr());
            tfLogradouro.setText(lista.get(tbClientes.getSelectedRow()).getLogradouro());
            tfNumero.setText(lista.get(tbClientes.getSelectedRow()).getNumero());
            tfBairro.setText(lista.get(tbClientes.getSelectedRow()).getBairro());
            cbCidade.setSelectedItem(lista.get(tbClientes.getSelectedRow()).getCidade().getCidade());
            tfUf.setText(lista.get(tbClientes.getSelectedRow()).getCidade().getUf());
            ftfCep.setText(lista.get(tbClientes.getSelectedRow()).getCep());
            ftfTelefone.setText(lista.get(tbClientes.getSelectedRow()).getTelefone());
            ftfCelular.setText(lista.get(tbClientes.getSelectedRow()).getCelular());
            tfCorCasa.setText(lista.get(tbClientes.getSelectedRow()).getCorCasa());
            tfNrFrente.setText(lista.get(tbClientes.getSelectedRow()).getNumeroCasaFrente());
            tfNrLado.setText(lista.get(tbClientes.getSelectedRow()).getNumeroCasaLado());
            tfApelido.setText(lista.get(tbClientes.getSelectedRow()).getApelido());
            tfReferencia.setText(lista.get(tbClientes.getSelectedRow()).getPontoReferencia());
            btEditar.setEnabled(true);
            btExcluir.setEnabled(true);
            operacao = 2;
        } else {
            limparCampos();
            editarCampos(false);
            reiniciaBotoes();
        }
    }

    private void InicializarTabela() {

        tbClientes.getColumnModel().getColumn(0).setPreferredWidth(400);
        tbClientes.setModel(tableModel);
        tbClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lms = tbClientes.getSelectionModel();
        lms.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    tbLinhaSelecionada(tbClientes);
                }
            }
        });
    }

    private void atualizarDadosDaTabela() {
        ClienteDAO dao = new ClienteDAO();
        lista = dao.listar(tfBusca.getText().trim().toUpperCase());

        if (tableModel.getRowCount() > 0) {
            limparTabela();
        }

        String[] campos = {null};


        for (int i = 0; i < lista.size(); i++) {
            tableModel.addRow(campos);
            tableModel.setValueAt(lista.get(i).getNome(), i, 0);
        }
    }

    private void limparTabela() {
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
    }
    //-Código referente a tabela--------------------------------------------------------------------------------

    private void novoCliente() {
        habilitaBotoesParaEdicao(true);
        limparCampos();
        operacao = 1;
    }

    private void editarCliente() {
        habilitaBotoesParaEdicao(true);
    }

    private void excluirCliente() {
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este cliente?", null, JOptionPane.OK_CANCEL_OPTION);
        System.out.println(opcao);
        if (opcao == 0) {
            ClienteDAO dao = new ClienteDAO();
            dao.excluir(clienteBean);
            reiniciaTela();
        }
    }

    private void salvar() {
        if(dadosValidos()){
            //setamos o objeto EquipeBean
        setaClienteBean();
        //Instanciamos o DAO
        ClienteDAO dao = new ClienteDAO();
        //verifica qual será a operação de peristência a ser realizada
        if (operacao == 1) {
            dao.inserir(clienteBean);
        }
        if (operacao == 2) {
            dao.alterar(clienteBean);
        }
        habilitaBotoesParaEdicao(false);
        reiniciaTela();
        }

    }

    private void habilitaBotoesParaEdicao(boolean edicao) {

        if (edicao) {
            btNovo.setEnabled(false);
            btEditar.setEnabled(false);
            btExcluir.setEnabled(false);
            btSalvar.setEnabled(true);
        } else {
            btNovo.setEnabled(true);
            btEditar.setEnabled(true);
            btExcluir.setEnabled(true);
            btSalvar.setEnabled(false);
        }
        editarCampos(edicao);
    }

    private void limparCampos() {
        tfNome.setText("");
        tfRg.setText("");
        ftfCpf.setText("");
        ftfNascimento.setText("");
        tfLogradouro.setText("");
        tfNumero.setText("");
        tfBairro.setText("");
        cbCidade.setSelectedIndex(0);
        tfUf.setText("");
        ftfCep.setText("");
        ftfTelefone.setText("");
        ftfCelular.setText("");
        tfApelido.setText("");
        tfNrFrente.setText("");
        tfNrLado.setText("");
        tfCorCasa.setText("");
        tfReferencia.setText("");
        tfNome.requestFocus();
    }

    private void editarCampos(boolean b) {
        tfNome.setEnabled(b);
        tfNome.setEnabled(b);
        tfRg.setEnabled(b);
        ftfCpf.setEnabled(b);
        ftfNascimento.setEnabled(b);
        tfLogradouro.setEnabled(b);
        tfNumero.setEnabled(b);
        tfBairro.setEnabled(b);
        cbCidade.setEnabled(b);
        btEditCidade.setEnabled(b);
        tfUf.setEnabled(b);
        ftfCep.setEnabled(b);
        ftfTelefone.setEnabled(b);
        ftfCelular.setEnabled(b);
        tfApelido.setEnabled(b);
        tfNrFrente.setEnabled(b);
        tfNrLado.setEnabled(b);
        tfCorCasa.setEnabled(b);
        tfReferencia.setEnabled(b);
        tbClientes.setEnabled(!b);
        tfNome.requestFocus();
    }

    public void reiniciaTela() {
        tbClientes.clearSelection();
        limparTabela();
        limparCampos();
        reiniciaBotoes();
        editarCampos(false);
        operacao = 0;
        btNovo.setEnabled(true);
    }

    private void reiniciaBotoes() {
        btNovo.setEnabled(true);
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
        btSalvar.setEnabled(false);
    }

    private void setaClienteBean() {
        //O clienteBean.setId() já foi setado no método tbLinhaSelecionada
        clienteBean.setNome(tfNome.getText());
        clienteBean.setRg(tfRg.getText());
        clienteBean.setCpf(ftfCpf.getText());
        clienteBean.setDataNascimento(ftfNascimento.getText());
        clienteBean.setLogradouro(tfLogradouro.getText().toUpperCase().trim());
        clienteBean.setNumero(tfNumero.getText().toUpperCase().trim());
        clienteBean.setBairro(tfBairro.getText().toUpperCase().trim());
        clienteBean.setCep(ftfCep.getText());
        clienteBean.setTelefone(ftfTelefone.getText());
        clienteBean.setCelular(ftfCelular.getText());
        clienteBean.setApelido(tfApelido.getText());
        clienteBean.setCorCasa(tfCorCasa.getText());
        clienteBean.setNumeroCasaFrente(tfNrFrente.getText());
        clienteBean.setNumeroCasaLado(tfNrLado.getText());
        clienteBean.setPontoReferencia(tfReferencia.getText());
    }

    private void carregaCbCidades() {
        cbCidade.removeAllItems();
        cbCidade.addItem("");        
        CidadeDAO dao = new CidadeDAO();
        cidades = dao.listar();
        for (int i = 0; i < cidades.size(); i++) {
            cbCidade.addItem(cidades.get(i).getCidade());
        }
    }

    public void atualizaCbCidades() {
        cidades.clear();
        CidadeDAO dao = new CidadeDAO();
        cidades = dao.listar();
        cbCidade.setSelectedIndex(0);
        //não removemos todos os itens de uma vez pois o método cbDiscriminacaoI é acionado
        //e caso não haja pelo menos 1 item lançara uma exceção.
        for (int i = cbCidade.getItemCount() - 1; i > 0; i--) {
            if (cbCidade.getItemCount() > 0) {
                cbCidade.removeItemAt(i);
            }
        }

        for (int i = 0; i < cidades.size(); i++) {
            cbCidade.addItem(cidades.get(i).getCidade());
        }
    }

    private void setaCidadeBean() {
        CidadeBean cidade = new CidadeBean();
        for (int i = 0; i < cidades.size(); i++) {
            if(cidades.get(i).getCidade().equals(cbCidade.getSelectedItem().toString())){
                tfUf.setText(cidades.get(i).getUf());
                cidade.setId(cidades.get(i).getId());
                cidade.setCidade(cidades.get(i).getCidade());
                cidade.setUf(cidades.get(i).getUf());
                clienteBean.setCidade(cidade);
                break;
            }
        }
    }

    private boolean dadosValidos() {
        if(clienteBean.getCidade() == null){
            JOptionPane.showMessageDialog(this, "Informe a cidade");
            cbCidade.requestFocus();
            return false;
        }else{
            return true;
        }
    }
}
