/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadAdmin.java
 *
 * Created on 13/06/2011, 14:54:29
 */
package br.com.devmax.sisgvc.visao;

import br.com.devmax.sisgvc.controle.Controle;
import br.com.devmax.sisgvc.daos.PerfilDAO;
import br.com.devmax.sisgvc.daos.UsuarioDAO;
import br.com.devmax.sisgvc.modelo.PerfilBean;
import br.com.devmax.sisgvc.modelo.UsuarioBean;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell
 */
public class FrmCadAdmin extends javax.swing.JDialog {

    /** Creates new form FrmCadAdmin */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FrmCadAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarCbPerfil();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbPerfil = new javax.swing.JComboBox();
        lbPerfil = new javax.swing.JLabel();
        ptfSenha = new javax.swing.JPasswordField();
        lbSenha = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        lbLogin = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbmsNome = new javax.swing.JLabel();
        lbmsNome.setVisible(false);
        lbmsSenha = new javax.swing.JLabel();
        lbmsSenha.setVisible(false);
        lbmsLogin = new javax.swing.JLabel();
        lbmsLogin.setVisible(false);
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISGVC - Sistema Gerenciador de Vendas por Consignação");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador" }));
        cbPerfil.setEnabled(false);

        lbPerfil.setText("Perfil:");

        ptfSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ptfSenhaFocusGained(evt);
            }
        });

        lbSenha.setText("Senha:");

        tfLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLoginFocusGained(evt);
            }
        });

        lbLogin.setText("Login:");

        tfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNomeFocusGained(evt);
            }
        });

        lbNome.setText("Nome:");

        lbmsNome.setForeground(new java.awt.Color(255, 0, 0));
        lbmsNome.setText("Informe o nome do administrador.");
        lbmsNome.setFocusable(false);

        lbmsSenha.setForeground(new java.awt.Color(255, 0, 0));
        lbmsSenha.setText("Informe a senha do administrador.");
        lbmsSenha.setFocusable(false);

        lbmsLogin.setForeground(new java.awt.Color(255, 0, 0));
        lbmsLogin.setText("Informe o login do administrador.");
        lbmsLogin.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbmsNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbmsLogin))
                    .addComponent(tfLogin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbmsSenha))
                            .addComponent(ptfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPerfil)
                            .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbmsNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(lbmsLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSenha)
                            .addComponent(lbmsSenha)
                            .addComponent(lbPerfil))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ptfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/User-Executive-Blue-32.png"))); // NOI18N
        jLabel1.setText("Cadastre o Administrador do Sistema");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btCadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-448)/2, (screenSize.height-315)/2, 448, 315);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrarAdministrador();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void tfNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeFocusGained
        lbmsNome.setVisible(false);
    }//GEN-LAST:event_tfNomeFocusGained

    private void tfLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoginFocusGained
        lbmsLogin.setVisible(false);
    }//GEN-LAST:event_tfLoginFocusGained

    private void ptfSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ptfSenhaFocusGained
        lbmsSenha.setVisible(false);
    }//GEN-LAST:event_ptfSenhaFocusGained
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

    public void run() {
    FrmCadAdmin dialog = new FrmCadAdmin(new javax.swing.JFrame(), true);
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

    @Override
    public void windowClosing(java.awt.event.WindowEvent e) {
    System.exit(0);
    }
    });
    dialog.setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JComboBox cbPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbmsLogin;
    private javax.swing.JLabel lbmsNome;
    private javax.swing.JLabel lbmsSenha;
    private javax.swing.JPasswordField ptfSenha;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    private static List<PerfilBean> perfis = new ArrayList<PerfilBean>();

    private void cadastrarAdministrador() {
        //verifica se os campos estão preenchidos.
        if (checarDados()) {
            //instancia um administrador do tipo usuário e seta os dados para seus atribuitos.
            UsuarioBean administrador = new UsuarioBean();
            administrador.setNoUsuario(tfNome.getText());
            administrador.setLogin(tfLogin.getText());
            administrador.setSenha(ptfSenha.getText());
            //setamos o perfil através do método getPerfilFromCB
            administrador.setPerfil(getPerfilFromCB(cbPerfil.getSelectedItem().toString()));

            UsuarioDAO dao = new UsuarioDAO();

            if (dao.inserir(administrador)) {
                Controle.listarUsuarios();
                dispose();
                Controle.abreFrmPrincipal();
                Controle.frmPrincipal.carregarBarradeStatus(administrador);
            } else {
                JOptionPane.showMessageDialog(this, "O usuário não foi cadastrado.");
            }
        }

    }

    private boolean checarDados() {
        boolean result = true;
        if (tfNome.getText().isEmpty()) {
            lbmsNome.setVisible(true);
            result = false;
        }
        if (tfLogin.getText().isEmpty()) {
            lbmsLogin.setVisible(true);
            result = false;
        }
        if (ptfSenha.getText().isEmpty()) {
            lbmsSenha.setVisible(true);
            result = false;
        }
        return result;
    }

    public void carregarCbPerfil() {

        PerfilDAO dao = new PerfilDAO();
        perfis = dao.listar();

        cbPerfil.removeAllItems();
        cbPerfil.addItem("Selecione um perfil");

        for (int i = 0; i < perfis.size(); i++) {
            cbPerfil.addItem(perfis.get(i).getNoPerfil());
        }

        cbPerfil.setSelectedIndex(1);
    }

    /**
     * Este método recebe uma String de um JComboBox e percorre a lista a procura
     * do elemento referente ao selecionado no combobox para ser setado no objeto bean.
     * @param item
     * @return PerfilBean
     */
    private PerfilBean getPerfilFromCB(String item) {
        PerfilBean perfil = new PerfilBean();
        for (int i = 0; i < perfis.size(); i++) {
            if (perfis.get(i).getNoPerfil().equals(item)) {
                perfil.setId(perfis.get(i).getId());
                perfil.setNoPerfil(perfis.get(i).getNoPerfil());
                perfil.setDsPerfil(perfis.get(i).getDsPerfil());
                break;
            }
        }
        return perfil;
    }
}
