/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadPerfil.java
 *
 * Created on 06/07/2011, 10:36:34
 */
package br.com.devmax.sisgvc.visao;

import br.com.devmax.sisgvc.daos.CompraDAO;
import br.com.devmax.sisgvc.modelo.CompraBean;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maxwell
 */
public class FrmCompras extends javax.swing.JDialog {

    /** Creates new form FrmCadPerfil */
    public FrmCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelBotoes = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISGVC - Sistema Gerenciador de Vendas por Consignação");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/file-new-16x16.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        painelBotoes.add(btNovo);

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/edit-16x16.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        painelBotoes.add(btEditar);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/edit-delete-16x16.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        painelBotoes.add(btExcluir);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/product-sales-report-32.png"))); // NOI18N
        jLabel1.setText("Compras");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/search-16x16.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tbVendas.setModel(tableModel);
        jScrollPane1.setViewportView(tbVendas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                    .addComponent(btPesquisar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPesquisar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1055)/2, (screenSize.height-659)/2, 1055, 659);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novoPedido();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        editarPedido();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirPedido();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        reiniciaTela();
    }//GEN-LAST:event_formWindowClosing

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        atualizarDadosDaTabela();
    }//GEN-LAST:event_btPesquisarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JTable tbVendas;
    // End of variables declaration//GEN-END:variables
    private static List<CompraBean> lista = new ArrayList<CompraBean>();
    private static CompraBean compraBean;
    //-Código referente a tabela--------------------------------------------------------------------------------
    private DefaultTableModel tableModel = new DefaultTableModel(null, new String[]{"Código","Nota Fiscal", "Fornecedor", "CNPJ", "Emissão", "Entrega"});
    private ListSelectionModel lms;


    private void tbLinhaSelecionada(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            compraBean = new CompraBean();
            compraBean.setId(lista.get(tb.getSelectedRow()).getId());
            compraBean.setNtFiscal(lista.get(tb.getSelectedRow()).getNtFiscal());
            compraBean.setFornecedor(lista.get(tb.getSelectedRow()).getFornecedor());
            compraBean.setDataEmissao(lista.get(tb.getSelectedRow()).getDataEmissao());
            compraBean.setDataEntrega(lista.get(tb.getSelectedRow()).getDataEntrega());
            btEditar.setEnabled(true);
            btExcluir.setEnabled(true);
            btNovo.setEnabled(false);
        } else {
            compraBean = null;
            reiniciaBotoes();

        }
    }

    private void inicializarTabela() {

        tbVendas.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbVendas.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbVendas.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbVendas.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbVendas.setModel(tableModel);
        tbVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lms = tbVendas.getSelectionModel();
        lms.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    tbLinhaSelecionada(tbVendas);
                }
            }
        });
        atualizarDadosDaTabela();
    }

    public void atualizarDadosDaTabela() {
        CompraDAO dao = new CompraDAO();
        lista = dao.listar();
               

        if (tableModel.getRowCount() > 0) {
            limparTabela();
        }

        String[] campos = {null,null, null, null, null, null};


        for (int i = 0; i < lista.size(); i++) {
            tableModel.addRow(campos);
            tableModel.setValueAt(lista.get(i).getId(), i, 0);
            tableModel.setValueAt(lista.get(i).getNtFiscal(), i, 1);
            tableModel.setValueAt(lista.get(i).getFornecedor().getNome(), i, 2);
            tableModel.setValueAt(lista.get(i).getFornecedor().getCnpj(), i, 3);
            tableModel.setValueAt(lista.get(i).getDataEmissaoStr(), i, 4);
            tableModel.setValueAt(lista.get(i).getDataEntregaStr(), i, 5);
        }
    }

    private void limparTabela() {
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
    }
    //-Código referente a tabela--------------------------------------------------------------------------------

    private void novoPedido() {
        habilitaBotoesParaEdicao(true);
        FrmCadCompra frmCadCompra = new FrmCadCompra(null, true, null);
        frmCadCompra.setVisible(true);
        
    }

    private void editarPedido() {
        habilitaBotoesParaEdicao(true);
        FrmCadCompra frmCadCompra = new FrmCadCompra(null, true, compraBean);
        frmCadCompra.setVisible(true);
        
    }

    private void excluirPedido() {
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esta compra?", null, JOptionPane.OK_CANCEL_OPTION);
        if (opcao == 0) {
            CompraDAO dao = new CompraDAO();
            dao.excluir(compraBean);
            reiniciaTela();
        }
    }

    private void habilitaBotoesParaEdicao(boolean edicao) {

        if (edicao) {
            btNovo.setEnabled(false);
            btEditar.setEnabled(false);
            btExcluir.setEnabled(false);
        } else {
            btNovo.setEnabled(true);
            btEditar.setEnabled(true);
            btExcluir.setEnabled(true);
        }

    }

    public void reiniciaTela() {
        tbVendas.clearSelection();
        atualizarDadosDaTabela();
        reiniciaBotoes();       
    }

    private void reiniciaBotoes() {
        btNovo.setEnabled(true);
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
    }    

    private void inicializarDatas() {
        Calendar dataInicial = Calendar.getInstance();
        dataInicial.setTime(new Date());
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        String novoFormato;
        novoFormato = formatador.format(dataInicial.getTime());
        //ftfDataFinal.setText(novoFormato);
        dataInicial.add(Calendar.DAY_OF_MONTH, -7);
        novoFormato = formatador.format(dataInicial.getTime());
        //ftfDataInicial.setText(novoFormato);
    }    
}
