/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPrincipal.java
 *
 * Created on 13/06/2011, 10:57:11
 */
package br.com.devmax.sisgvc.visao;

import br.com.devmax.sisgvc.controle.Controle;
import br.com.devmax.sisgvc.daos.PedidoDAO;
import br.com.devmax.sisgvc.modelo.PrivilegioBean;
import br.com.devmax.sisgvc.modelo.UsuarioBean;
import br.com.devmax.sisgvc.modelo.Utilidades;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FrmPrincipal() {
        initComponents();
        //habilitarMenus(false);
        System.gc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuarioStatusBar = new javax.swing.JLabel();
        lbPerfilStatusBar = new javax.swing.JLabel();
        btPedidos = new javax.swing.JButton();
        btVendas = new javax.swing.JButton();
        btCompras = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        mnuAcesso = new javax.swing.JMenu();
        mnuLoginLogoff = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuControleAcesso = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuClientes = new javax.swing.JMenuItem();
        mnuCidades = new javax.swing.JMenuItem();
        mnuEquipes = new javax.swing.JMenuItem();
        mnuFornecedores = new javax.swing.JMenuItem();
        mnuFuncionarios = new javax.swing.JMenuItem();
        mnuMedidas = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenuItem();
        mnuMovimento = new javax.swing.JMenu();
        mnuPedidos = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenuItem();
        mnuCompras = new javax.swing.JMenuItem();
        mnuFerramentas = new javax.swing.JMenu();
        mnuDatabase = new javax.swing.JMenu();
        mnuConfigDatabase = new javax.swing.JMenuItem();
        mnuBackup = new javax.swing.JMenuItem();
        mnuRestore = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuProducaoVendedor = new javax.swing.JMenuItem();
        mnuVendasProdutos = new javax.swing.JMenuItem();
        mnuRelClientes = new javax.swing.JMenu();
        mnuVendasCliente = new javax.swing.JMenuItem();
        mnuConsolidadoCliente = new javax.swing.JMenuItem();
        mnuDetalhadoCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISGVC - Sistema Gerenciador de Vendas por Consignação");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbUsuarioStatusBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPerfilStatusBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/product-sales-report-32.png"))); // NOI18N
        btPedidos.setText("Pedidos");
        btPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosActionPerformed(evt);
            }
        });

        btVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/fiat_uno32.jpg"))); // NOI18N
        btVendas.setText("Vendas");
        btVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendasActionPerformed(evt);
            }
        });

        btCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/truck-32.png"))); // NOI18N
        btCompras.setText("Compras");
        btCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprasActionPerformed(evt);
            }
        });

        mnuAcesso.setText("Acesso");

        mnuLoginLogoff.setText("Logoff");
        mnuLoginLogoff.setEnabled(false);
        mnuLoginLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoginLogoffActionPerformed(evt);
            }
        });
        mnuAcesso.add(mnuLoginLogoff);

        menu.add(mnuAcesso);

        mnuCadastro.setText("Cadastros");

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/User-Executive-Blue-16.png"))); // NOI18N
        mnuUsuarios.setText("Usuários");
        mnuUsuarios.setName("Cadastro de Usuários"); // NOI18N
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuUsuarios);

        mnuControleAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/control_panel_access16.png"))); // NOI18N
        mnuControleAcesso.setText("Controle de Acesso");
        mnuControleAcesso.setName("Perfis de Usuário"); // NOI18N
        mnuControleAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuControleAcessoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuControleAcesso);
        mnuCadastro.add(jSeparator1);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/User-Group-16_1.png"))); // NOI18N
        mnuClientes.setText("Clientes");
        mnuClientes.setName("Cadastro de Clientes"); // NOI18N
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuClientes);

        mnuCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/city16.png"))); // NOI18N
        mnuCidades.setText("Cidades");
        mnuCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCidadesActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCidades);

        mnuEquipes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/fiat_uno16.jpg"))); // NOI18N
        mnuEquipes.setText("Equipes");
        mnuEquipes.setName("Cadastro de Equipes"); // NOI18N
        mnuEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEquipesActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuEquipes);

        mnuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/truck-16.png"))); // NOI18N
        mnuFornecedores.setText("Fornecedores");
        mnuFornecedores.setName("Cadastro de Fornecedores"); // NOI18N
        mnuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuFornecedores);

        mnuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/Clients-16.png"))); // NOI18N
        mnuFuncionarios.setText("Funcionários");
        mnuFuncionarios.setName("Cadastro de Funcionários"); // NOI18N
        mnuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFuncionariosActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuFuncionarios);

        mnuMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/Units-2-16.png"))); // NOI18N
        mnuMedidas.setText("Medidas");
        mnuMedidas.setName("Cadastro de Medidas"); // NOI18N
        mnuMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMedidasActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuMedidas);

        mnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/inventory-maintenance-icon1.png"))); // NOI18N
        mnuProdutos.setText("Produtos");
        mnuProdutos.setName("Cadastro de Produtos"); // NOI18N
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuProdutos);

        menu.add(mnuCadastro);

        mnuMovimento.setText("Movimento");

        mnuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/product-sales-report-16.png"))); // NOI18N
        mnuPedidos.setText("Pedidos");
        mnuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPedidosActionPerformed(evt);
            }
        });
        mnuMovimento.add(mnuPedidos);

        mnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/fiat_uno16.jpg"))); // NOI18N
        mnuVendas.setText("Vendas");
        mnuVendas.setActionCommand("Equipes");
        mnuVendas.setEnabled(false);
        mnuVendas.setName("Movimento de Equipes"); // NOI18N
        mnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendasActionPerformed(evt);
            }
        });
        mnuMovimento.add(mnuVendas);

        mnuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/truck-16.png"))); // NOI18N
        mnuCompras.setText("Compras");
        mnuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComprasActionPerformed(evt);
            }
        });
        mnuMovimento.add(mnuCompras);

        menu.add(mnuMovimento);

        mnuFerramentas.setText("Ferramentas");

        mnuDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/database16.png"))); // NOI18N
        mnuDatabase.setText("Banco de Dados");

        mnuConfigDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/application_form16.png"))); // NOI18N
        mnuConfigDatabase.setText("Configurações de Acesso");
        mnuConfigDatabase.setEnabled(false);
        mnuDatabase.add(mnuConfigDatabase);

        mnuBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/backup_manager16.png"))); // NOI18N
        mnuBackup.setText("Copiar Base de Dados");
        mnuBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBackupActionPerformed(evt);
            }
        });
        mnuDatabase.add(mnuBackup);

        mnuRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/devmax/sisgvc/visao/img/backup-restore16.png"))); // NOI18N
        mnuRestore.setText("Restaurar Base de Dados");
        mnuRestore.setEnabled(false);
        mnuDatabase.add(mnuRestore);

        mnuFerramentas.add(mnuDatabase);

        menu.add(mnuFerramentas);

        mnuRelatorios.setText("Relatórios");

        mnuProducaoVendedor.setText("Produção por Vendedor");
        mnuProducaoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProducaoVendedorActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuProducaoVendedor);

        mnuVendasProdutos.setText("Vendas de Produtos");
        mnuVendasProdutos.setEnabled(false);
        mnuVendasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendasProdutosActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuVendasProdutos);

        mnuRelClientes.setText("Clientes");

        mnuVendasCliente.setText("Vendas por Cliente");
        mnuVendasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendasClienteActionPerformed(evt);
            }
        });
        mnuRelClientes.add(mnuVendasCliente);

        mnuConsolidadoCliente.setText("Consolidado de Pedidos");
        mnuConsolidadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsolidadoClienteActionPerformed(evt);
            }
        });
        mnuRelClientes.add(mnuConsolidadoCliente);

        mnuDetalhadoCliente.setText("Detalhado de Pedidos");
        mnuDetalhadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDetalhadoClienteActionPerformed(evt);
            }
        });
        mnuRelClientes.add(mnuDetalhadoCliente);

        mnuRelatorios.add(mnuRelClientes);

        menu.add(mnuRelatorios);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUsuarioStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPerfilStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btPedidos)
                        .addGap(18, 18, 18)
                        .addComponent(btVendas)
                        .addGap(18, 18, 18)
                        .addComponent(btCompras)))
                .addContainerGap(572, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbPerfilStatusBar, lbUsuarioStatusBar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCompras, btPedidos, btVendas});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPedidos)
                    .addComponent(btVendas)
                    .addComponent(btCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuarioStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerfilStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbPerfilStatusBar, lbUsuarioStatusBar});

        setSize(new java.awt.Dimension(1016, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLoginLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoginLogoffActionPerformed
        if (mnuLoginLogoff.getText().equals("Logoff")) {
            lbPerfilStatusBar.setText("Perfil:");
            lbUsuarioStatusBar.setText("Usuário:");
            mnuLoginLogoff.setText("Login");
            habilitarMenus(false);
        }
        if (mnuLoginLogoff.getText().equals("Login")) {
            Controle.abreFrmAcesso();
        }

    }//GEN-LAST:event_mnuLoginLogoffActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        Controle.abreFrmUsuarios();
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuControleAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuControleAcessoActionPerformed
        Controle.abreFrmPerfis();
    }//GEN-LAST:event_mnuControleAcessoActionPerformed

    private void mnuEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEquipesActionPerformed
        Controle.abreFrmCadEquipe();
    }//GEN-LAST:event_mnuEquipesActionPerformed

    private void mnuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFuncionariosActionPerformed
        Controle.abreFrmCadFuncionario();
    }//GEN-LAST:event_mnuFuncionariosActionPerformed

    private void mnuMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMedidasActionPerformed
        Controle.abreFrmCadMedidas();
    }//GEN-LAST:event_mnuMedidasActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
        Controle.abreFrmCadProdutos();
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        Controle.abreFrmCadCliente();
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFornecedoresActionPerformed
        Controle.abreFrmCadFornecedor();
    }//GEN-LAST:event_mnuFornecedoresActionPerformed

    private void mnuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComprasActionPerformed
        Controle.abreFrmCompras();
    }//GEN-LAST:event_mnuComprasActionPerformed

    private void mnuProducaoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProducaoVendedorActionPerformed
        FrmProducaoVendas frmProducaoVendas = null;
        PedidoDAO dao = new PedidoDAO();
        dao.correcaoDevolvidoZerado();
        if (frmProducaoVendas == null) {
            frmProducaoVendas = new FrmProducaoVendas(this, false);
            frmProducaoVendas.setVisible(true);
        } else {
            frmProducaoVendas.setVisible(true);
        }
    }//GEN-LAST:event_mnuProducaoVendedorActionPerformed

    private void mnuVendasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendasClienteActionPerformed
        Controle.abreFrmVendasPorCliente();
    }//GEN-LAST:event_mnuVendasClienteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Utilidades.realizarBackupSQL();
    }//GEN-LAST:event_formWindowClosing

    private void mnuBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBackupActionPerformed
        Utilidades.realizarBackupSQL();
    }//GEN-LAST:event_mnuBackupActionPerformed

    private void mnuCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCidadesActionPerformed
        Controle.abreFrmCadCidades();
    }//GEN-LAST:event_mnuCidadesActionPerformed

    private void mnuVendasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendasProdutosActionPerformed
        FrmVendasPorProduto frm = new FrmVendasPorProduto(this, false);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuVendasProdutosActionPerformed

    private void mnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendasActionPerformed
        //Controle.abreFrmSaidaEquipes();
        JOptionPane.showMessageDialog(this, "Módulo em fase de desenvolvimento!","Informação",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuVendasActionPerformed

    private void btPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosActionPerformed
        Controle.abreFrmPedidos();
    }//GEN-LAST:event_btPedidosActionPerformed

    private void btVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendasActionPerformed
        //Controle.abreFrmSaidaEquipes();
        JOptionPane.showMessageDialog(this, "Módulo em fase de desenvolvimento!","Informação",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btVendasActionPerformed

    private void btComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprasActionPerformed
        Controle.abreFrmCadFornecedor();
    }//GEN-LAST:event_btComprasActionPerformed

    private void mnuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPedidosActionPerformed
        Controle.abreFrmPedidos();
    }//GEN-LAST:event_mnuPedidosActionPerformed

    private void mnuConsolidadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsolidadoClienteActionPerformed
        FrmRelConsolidadoPedidos frm = new FrmRelConsolidadoPedidos(this, false);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuConsolidadoClienteActionPerformed

    private void mnuDetalhadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDetalhadoClienteActionPerformed
        FrmRelDetalhadoPedidos frm = new FrmRelDetalhadoPedidos(this, false);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuDetalhadoClienteActionPerformed
    /**
     * @param args the command line arguments
     *//*
     public static void main(String args[]) {
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new FrmPrincipal().setVisible(true);
     }
     });
     }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompras;
    private javax.swing.JButton btPedidos;
    private javax.swing.JButton btVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbPerfilStatusBar;
    private javax.swing.JLabel lbUsuarioStatusBar;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu mnuAcesso;
    private javax.swing.JMenuItem mnuBackup;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCidades;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuCompras;
    private javax.swing.JMenuItem mnuConfigDatabase;
    private javax.swing.JMenuItem mnuConsolidadoCliente;
    private javax.swing.JMenuItem mnuControleAcesso;
    private javax.swing.JMenu mnuDatabase;
    private javax.swing.JMenuItem mnuDetalhadoCliente;
    private javax.swing.JMenuItem mnuEquipes;
    private javax.swing.JMenu mnuFerramentas;
    private javax.swing.JMenuItem mnuFornecedores;
    private javax.swing.JMenuItem mnuFuncionarios;
    private javax.swing.JMenuItem mnuLoginLogoff;
    private javax.swing.JMenuItem mnuMedidas;
    private javax.swing.JMenu mnuMovimento;
    private javax.swing.JMenuItem mnuPedidos;
    private javax.swing.JMenuItem mnuProducaoVendedor;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenu mnuRelClientes;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenuItem mnuRestore;
    private javax.swing.JMenuItem mnuUsuarios;
    private javax.swing.JMenuItem mnuVendas;
    private javax.swing.JMenuItem mnuVendasCliente;
    private javax.swing.JMenuItem mnuVendasProdutos;
    // End of variables declaration//GEN-END:variables

    //private static List<PrivilegioBean> privilegios = new ArrayList<PrivilegioBean>();
    public void carregarBarradeStatus(UsuarioBean usuario) {
        lbUsuarioStatusBar.setText("Usuário: " + usuario.getLogin().toUpperCase());
        lbPerfilStatusBar.setText("Perfil: " + usuario.getPerfil().getNoPerfil());
        mnuLoginLogoff.setText("Logoff");
        Controle.setUsuario(usuario);
        autorizarAcessoAsRotinas(usuario);
    }

    public void negarAcessoAsRotinas() {
        mnuCadastro.setEnabled(false);
        mnuMovimento.setEnabled(false);
        mnuFerramentas.setEnabled(false);
    }

    public void autorizarAcessoAsRotinas(UsuarioBean usuarioBean) {
        List<PrivilegioBean> privilegios = new ArrayList<PrivilegioBean>();
        Controle.listarPrivilegios();
        privilegios = Controle.getPrivilegios();

        for (int i = 0; i < privilegios.size(); i++) {

            if (privilegios.get(i).getPerfil().getNoPerfil().equals(usuarioBean.getPerfil().getNoPerfil())) {
                //setamos o perfil selecionado para o objeto statico perfil que
                //será utilizado para realiar persistência ao marcar ou desmarcar algum checkbox

                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuUsuarios.getName())) {
                    mnuUsuarios.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuControleAcesso.getName())) {
                    mnuControleAcesso.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuClientes.getName())) {
                    mnuClientes.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuEquipes.getName())) {
                    mnuEquipes.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuFornecedores.getName())) {
                    mnuFornecedores.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuFuncionarios.getName())) {
                    mnuFuncionarios.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuMedidas.getName())) {
                    mnuMedidas.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuProdutos.getName())) {
                    mnuProdutos.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuPedidos.getName())) {
                    mnuPedidos.setEnabled(privilegios.get(i).getAcessar());
                }
                if (privilegios.get(i).getRotina().getNomeRotina().equalsIgnoreCase(mnuVendas.getName())) {
                    mnuVendas.setEnabled(privilegios.get(i).getAcessar());
                }
            }
        }
    }

    public void habilitarMenus(Boolean b) {
        mnuCadastro.setEnabled(b);
        mnuMovimento.setEnabled(b);
        btCompras.setEnabled(b);
        btPedidos.setEnabled(b);
        btVendas.setEnabled(b);
    }
}
